var annotated_dup =
[
    [ "biovoltron", null, [
      [ "detail", null, [
        [ "policy", null, [
          [ "RoundRobin", "classbiovoltron_1_1detail_1_1policy_1_1RoundRobin.html", null ]
        ] ],
        [ "XbitConstIterator", "structbiovoltron_1_1detail_1_1XbitConstIterator.html", "structbiovoltron_1_1detail_1_1XbitConstIterator" ],
        [ "XbitIterator", "structbiovoltron_1_1detail_1_1XbitIterator.html", "structbiovoltron_1_1detail_1_1XbitIterator" ],
        [ "XbitIteratorBase", "classbiovoltron_1_1detail_1_1XbitIteratorBase.html", "classbiovoltron_1_1detail_1_1XbitIteratorBase" ],
        [ "XbitReference", "classbiovoltron_1_1detail_1_1XbitReference.html", "classbiovoltron_1_1detail_1_1XbitReference" ],
        [ "XbitVector", "classbiovoltron_1_1detail_1_1XbitVector.html", "classbiovoltron_1_1detail_1_1XbitVector" ],
        [ "XbitVectorBase", "classbiovoltron_1_1detail_1_1XbitVectorBase.html", "classbiovoltron_1_1detail_1_1XbitVectorBase" ]
      ] ],
      [ "kiss", null, [
        [ "PackedDNAString", "structbiovoltron_1_1kiss_1_1PackedDNAString.html", null ],
        [ "ThreadCache", "structbiovoltron_1_1kiss_1_1ThreadCache.html", null ],
        [ "ThreadState", "structbiovoltron_1_1kiss_1_1ThreadState.html", null ]
      ] ],
      [ "mirna", null, [
        [ "LenExp", "structbiovoltron_1_1mirna_1_1LenExp.html", null ],
        [ "MirExp", "structbiovoltron_1_1mirna_1_1MirExp.html", null ],
        [ "TailExp", "structbiovoltron_1_1mirna_1_1TailExp.html", null ]
      ] ],
      [ "paired", "namespacebiovoltron_1_1paired.html", [
        [ "AdapterTrimmer", "classbiovoltron_1_1paired_1_1AdapterTrimmer.html", "classbiovoltron_1_1paired_1_1AdapterTrimmer" ]
      ] ],
      [ "quantile", null, [
        [ "QuantileDataHelperType", "structbiovoltron_1_1quantile_1_1QuantileDataHelperType.html", "structbiovoltron_1_1quantile_1_1QuantileDataHelperType" ]
      ] ],
      [ "single", null, [
        [ "AdapterTrimmer", "classbiovoltron_1_1single_1_1AdapterTrimmer.html", "classbiovoltron_1_1single_1_1AdapterTrimmer" ]
      ] ],
      [ "AdapterAssembler", "classbiovoltron_1_1AdapterAssembler.html", "classbiovoltron_1_1AdapterAssembler" ],
      [ "AdapterGraph", "structbiovoltron_1_1AdapterGraph.html", null ],
      [ "AFCalculator", "structbiovoltron_1_1AFCalculator.html", null ],
      [ "Alignment", "structbiovoltron_1_1Alignment.html", null ],
      [ "AlleleUtils", "classbiovoltron_1_1AlleleUtils.html", null ],
      [ "Annotator", "structbiovoltron_1_1Annotator.html", null ],
      [ "AnyField", "structbiovoltron_1_1AnyField.html", null ],
      [ "Assembler", "classbiovoltron_1_1Assembler.html", null ],
      [ "AvxPairHMM", "structbiovoltron_1_1AvxPairHMM.html", null ],
      [ "AvxSmithWaterman", "structbiovoltron_1_1AvxSmithWaterman.html", null ],
      [ "BedGraphRecord", "structbiovoltron_1_1BedGraphRecord.html", "structbiovoltron_1_1BedGraphRecord" ],
      [ "BedHeader", "structbiovoltron_1_1BedHeader.html", null ],
      [ "BedRecord", "structbiovoltron_1_1BedRecord.html", "structbiovoltron_1_1BedRecord" ],
      [ "BedSixRecord", "structbiovoltron_1_1BedSixRecord.html", "structbiovoltron_1_1BedSixRecord" ],
      [ "BurrowWheelerAligner", "structbiovoltron_1_1BurrowWheelerAligner.html", "structbiovoltron_1_1BurrowWheelerAligner" ],
      [ "Cigar", "structbiovoltron_1_1Cigar.html", "structbiovoltron_1_1Cigar" ],
      [ "Codec", "structbiovoltron_1_1Codec.html", null ],
      [ "DeprecatedThreadPool", "classbiovoltron_1_1DeprecatedThreadPool.html", null ],
      [ "DepthPerAllele", "classbiovoltron_1_1DepthPerAllele.html", null ],
      [ "dna4", "classbiovoltron_1_1dna4.html", "classbiovoltron_1_1dna4" ],
      [ "dna5", "classbiovoltron_1_1dna5.html", "classbiovoltron_1_1dna5" ],
      [ "DuplicateReadFilter", "structbiovoltron_1_1DuplicateReadFilter.html", "structbiovoltron_1_1DuplicateReadFilter" ],
      [ "FastaRecord", "structbiovoltron_1_1FastaRecord.html", "structbiovoltron_1_1FastaRecord" ],
      [ "FastqRecord", "structbiovoltron_1_1FastqRecord.html", "structbiovoltron_1_1FastqRecord" ],
      [ "FisherStrand", "classbiovoltron_1_1FisherStrand.html", null ],
      [ "FMIndex", "classbiovoltron_1_1FMIndex.html", "classbiovoltron_1_1FMIndex" ],
      [ "Genotyper", "classbiovoltron_1_1Genotyper.html", null ],
      [ "GenotypeUtils", "structbiovoltron_1_1GenotypeUtils.html", null ],
      [ "GffRecord", "structbiovoltron_1_1GffRecord.html", "structbiovoltron_1_1GffRecord" ],
      [ "Graph", "classbiovoltron_1_1Graph.html", "classbiovoltron_1_1Graph" ],
      [ "GraphWrapper", "structbiovoltron_1_1GraphWrapper.html", "structbiovoltron_1_1GraphWrapper" ],
      [ "gzstreambase", "classbiovoltron_1_1gzstreambase.html", null ],
      [ "gzstreambuf", "classbiovoltron_1_1gzstreambuf.html", null ],
      [ "Haplotype", "structbiovoltron_1_1Haplotype.html", null ],
      [ "HaplotypeAssembler", "classbiovoltron_1_1HaplotypeAssembler.html", null ],
      [ "HaplotypeCaller", "structbiovoltron_1_1HaplotypeCaller.html", "structbiovoltron_1_1HaplotypeCaller" ],
      [ "HaplotypeGraph", "structbiovoltron_1_1HaplotypeGraph.html", "structbiovoltron_1_1HaplotypeGraph" ],
      [ "Header", "structbiovoltron_1_1Header.html", null ],
      [ "HeaderableRecord", "structbiovoltron_1_1HeaderableRecord.html", null ],
      [ "Hit", "structbiovoltron_1_1Hit.html", null ],
      [ "Hs37d5", "structbiovoltron_1_1Hs37d5.html", null ],
      [ "IBamStream", "structbiovoltron_1_1IBamStream.html", "structbiovoltron_1_1IBamStream" ],
      [ "igzstream", "classbiovoltron_1_1igzstream.html", null ],
      [ "Index", "structbiovoltron_1_1Index.html", "structbiovoltron_1_1Index" ],
      [ "Interval", "structbiovoltron_1_1Interval.html", "structbiovoltron_1_1Interval" ],
      [ "IntervalTree", "structbiovoltron_1_1IntervalTree.html", null ],
      [ "KISS1Sorter", "structbiovoltron_1_1KISS1Sorter.html", null ],
      [ "KISS2Sorter", "structbiovoltron_1_1KISS2Sorter.html", null ],
      [ "KPsaisSorter", "structbiovoltron_1_1KPsaisSorter.html", null ],
      [ "MappingQualityReadFilter", "structbiovoltron_1_1MappingQualityReadFilter.html", "structbiovoltron_1_1MappingQualityReadFilter" ],
      [ "MateOnSameContigReadFilter", "structbiovoltron_1_1MateOnSameContigReadFilter.html", "structbiovoltron_1_1MateOnSameContigReadFilter" ],
      [ "MathUtils", "structbiovoltron_1_1MathUtils.html", null ],
      [ "MemAln", "structbiovoltron_1_1MemAln.html", "structbiovoltron_1_1MemAln" ],
      [ "MinimumLengthReadFilter", "structbiovoltron_1_1MinimumLengthReadFilter.html", "structbiovoltron_1_1MinimumLengthReadFilter" ],
      [ "Mismatch", "structbiovoltron_1_1Mismatch.html", null ],
      [ "OBamStream", "structbiovoltron_1_1OBamStream.html", "structbiovoltron_1_1OBamStream" ],
      [ "ogzstream", "classbiovoltron_1_1ogzstream.html", null ],
      [ "PairHMM", "structbiovoltron_1_1PairHMM.html", null ],
      [ "PsaisSorter", "structbiovoltron_1_1PsaisSorter.html", null ],
      [ "QualityUtils", "structbiovoltron_1_1QualityUtils.html", null ],
      [ "RangeUtils", "structbiovoltron_1_1RangeUtils.html", null ],
      [ "ReadClipper", "structbiovoltron_1_1ReadClipper.html", null ],
      [ "Record", "structbiovoltron_1_1Record.html", null ],
      [ "ReferenceConfidenceModel", "structbiovoltron_1_1ReferenceConfidenceModel.html", null ],
      [ "ReferenceRecord", "structbiovoltron_1_1ReferenceRecord.html", "structbiovoltron_1_1ReferenceRecord" ],
      [ "SaisSorter", "structbiovoltron_1_1SaisSorter.html", null ],
      [ "SamHeader", "structbiovoltron_1_1SamHeader.html", null ],
      [ "SamRecord", "structbiovoltron_1_1SamRecord.html", "structbiovoltron_1_1SamRecord" ],
      [ "SamUtil", "structbiovoltron_1_1SamUtil.html", "structbiovoltron_1_1SamUtil" ],
      [ "SecondaryAlignmentReadFilter", "structbiovoltron_1_1SecondaryAlignmentReadFilter.html", "structbiovoltron_1_1SecondaryAlignmentReadFilter" ],
      [ "Serializer", "structbiovoltron_1_1Serializer.html", null ],
      [ "SIMDAlignment", "structbiovoltron_1_1SIMDAlignment.html", "structbiovoltron_1_1SIMDAlignment" ],
      [ "SimdAlignmentEngine", "classbiovoltron_1_1SimdAlignmentEngine.html", "classbiovoltron_1_1SimdAlignmentEngine" ],
      [ "SmithWaterman", "structbiovoltron_1_1SmithWaterman.html", "structbiovoltron_1_1SmithWaterman" ],
      [ "SseSmithWaterman", "structbiovoltron_1_1SseSmithWaterman.html", "structbiovoltron_1_1SseSmithWaterman" ],
      [ "StableSorter", "structbiovoltron_1_1StableSorter.html", "structbiovoltron_1_1StableSorter" ],
      [ "Tailor", "structbiovoltron_1_1Tailor.html", null ],
      [ "ThreadPool", "classbiovoltron_1_1ThreadPool.html", "classbiovoltron_1_1ThreadPool" ],
      [ "Variant", "structbiovoltron_1_1Variant.html", null ],
      [ "VcfHeader", "structbiovoltron_1_1VcfHeader.html", null ],
      [ "VcfRecord", "structbiovoltron_1_1VcfRecord.html", "structbiovoltron_1_1VcfRecord" ],
      [ "VcfUtil", "structbiovoltron_1_1VcfUtil.html", null ],
      [ "WigFixedStepRecord", "structbiovoltron_1_1WigFixedStepRecord.html", null ],
      [ "WigHeader", "structbiovoltron_1_1WigHeader.html", null ],
      [ "WigVarStepRecord", "structbiovoltron_1_1WigVarStepRecord.html", null ],
      [ "Worker", "classbiovoltron_1_1Worker.html", "classbiovoltron_1_1Worker" ]
    ] ],
    [ "skewer", null, [
      [ "cData", "classskewer_1_1cData.html", null ],
      [ "cFQ", "classskewer_1_1cFQ.html", null ],
      [ "cParameter", "classskewer_1_1cParameter.html", null ],
      [ "cStats", "classskewer_1_1cStats.html", null ],
      [ "cTaskManager", "classskewer_1_1cTaskManager.html", null ],
      [ "cWork", "classskewer_1_1cWork.html", null ],
      [ "OPTION_ITEM", "structskewer_1_1OPTION__ITEM.html", null ],
      [ "tag_CFILE", "structskewer_1_1tag__CFILE.html", null ],
      [ "tag_LINE", "structskewer_1_1tag__LINE.html", null ],
      [ "tag_mtaux_t", "structskewer_1_1tag__mtaux__t.html", null ],
      [ "tag_REC", "structskewer_1_1tag__REC.html", null ],
      [ "TASK", "structskewer_1_1TASK.html", null ]
    ] ],
    [ "AlignedAllocator", "classAlignedAllocator.html", "classAlignedAllocator" ],
    [ "cAdapter", "classcAdapter.html", null ],
    [ "cElementSet", "classcElementSet.html", null ],
    [ "cMatrix", "classcMatrix.html", null ],
    [ "ELEMENT", "structELEMENT.html", null ],
    [ "ElementComparator", "classElementComparator.html", null ],
    [ "tag_INDEX", "structtag__INDEX.html", null ]
];