var searchData=
[
  ['a_20fasta_20file_0',['Step 3. Reading Data from a FASTA File',['../tutorials-fileio-fasta.html#autotoc_md23',1,'']]],
  ['a_20fastarecord_20object_1',['Step 2. Creating a FastaRecord Object',['../tutorials-fileio-fasta.html#autotoc_md22',1,'']]],
  ['a_20glance_2',['Biovoltron at a Glance',['../index.html#autotoc_md10',1,'']]],
  ['adapterassembler_3',['AdapterAssembler',['../classbiovoltron_1_1AdapterAssembler.html',1,'biovoltron']]],
  ['adaptergraph_4',['AdapterGraph',['../structbiovoltron_1_1AdapterGraph.html',1,'biovoltron']]],
  ['adaptertrimmer_5',['AdapterTrimmer',['../classbiovoltron_1_1paired_1_1AdapterTrimmer.html',1,'biovoltron::paired::AdapterTrimmer&lt; R &gt;'],['../classbiovoltron_1_1single_1_1AdapterTrimmer.html',1,'biovoltron::single::AdapterTrimmer&lt; R &gt;']]],
  ['adaptertrimmer_3c_20record_20_3e_6',['AdapterTrimmer&lt; Record &gt;',['../classbiovoltron_1_1paired_1_1AdapterTrimmer.html',1,'biovoltron::paired::AdapterTrimmer&lt; Record &gt;'],['../classbiovoltron_1_1single_1_1AdapterTrimmer.html',1,'biovoltron::single::AdapterTrimmer&lt; Record &gt;']]],
  ['adaptor_20trimming_7',['Adaptor Trimming',['../index.html#autotoc_md13',1,'']]],
  ['afcalculator_8',['AFCalculator',['../structbiovoltron_1_1AFCalculator.html',1,'biovoltron']]],
  ['algo_9',['algo',['../group__algo.html',1,'']]],
  ['align_10',['align',['../group__align.html',1,'']]],
  ['align_20and_20variant_20calling_11',['Align and Variant Calling',['../index.html#autotoc_md12',1,'']]],
  ['aligner_12',['Burrow Wheeler Aligner',['../benchmark.html#autotoc_md0',1,'']]],
  ['alignment_13',['Alignment',['../structbiovoltron_1_1Alignment.html',1,'biovoltron']]],
  ['alignment_20tutorials_14',['Alignment Tutorials',['../tutorials.html#tutorials-alignment',1,'']]],
  ['alleleutils_15',['AlleleUtils',['../classbiovoltron_1_1AlleleUtils.html',1,'biovoltron']]],
  ['aln_16',['Aln',['../structbiovoltron_1_1BurrowWheelerAligner_1_1Aln.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['alnpair_17',['AlnPair',['../structbiovoltron_1_1BurrowWheelerAligner_1_1AlnPair.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['alt_18',['alt',['../structbiovoltron_1_1VcfRecord.html#a03a582fdcf4de770cea2d0e5622cd5f2',1,'biovoltron::VcfRecord']]],
  ['anchor_19',['Anchor',['../structbiovoltron_1_1BurrowWheelerAligner_1_1Anchor.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['and_20output_20',['File Input and Output',['../index.html#autotoc_md11',1,'']]],
  ['and_20running_21',['Compiling and Running',['../installation.html#autotoc_md19',1,'']]],
  ['and_20support_22',['Community and Support',['../index.html#autotoc_md15',1,'']]],
  ['and_20variant_20calling_23',['Align and Variant Calling',['../index.html#autotoc_md12',1,'']]],
  ['annotate_24',['annotate',['../group__annotate.html',1,'']]],
  ['annotator_25',['Annotator',['../structbiovoltron_1_1Annotator.html',1,'biovoltron']]],
  ['annotator_20tutorials_26',['Annotator Tutorials',['../tutorials.html#tutorials-annotator',1,'']]],
  ['anyfield_27',['AnyField',['../structbiovoltron_1_1AnyField.html',1,'biovoltron']]],
  ['append_28',['append',['../structbiovoltron_1_1Cigar.html#a0d5d66e54cbf1e52d2d6c90e4b6e8002',1,'biovoltron::Cigar']]],
  ['applications_29',['applications',['../group__applications.html',1,'']]],
  ['assemble_30',['assemble',['../classbiovoltron_1_1AdapterAssembler.html#a269f31e75ed3c000be5391238f1be4c6',1,'biovoltron::AdapterAssembler::assemble()'],['../group__assemble.html',1,'assemble']]],
  ['assembler_31',['Assembler',['../classbiovoltron_1_1Assembler.html',1,'biovoltron']]],
  ['at_20a_20glance_32',['Biovoltron at a Glance',['../index.html#autotoc_md10',1,'']]],
  ['attrs_33',['attrs',['../structbiovoltron_1_1GffRecord.html#afd2ce8e23af19324eb91abac25292cec',1,'biovoltron::GffRecord']]],
  ['avxpairhmm_34',['AvxPairHMM',['../structbiovoltron_1_1AvxPairHMM.html',1,'biovoltron']]],
  ['avxsmithwaterman_35',['AvxSmithWaterman',['../structbiovoltron_1_1AvxSmithWaterman.html',1,'biovoltron']]]
];
