var searchData=
[
  ['a_20fasta_20file_0',['Step 3. Reading Data from a FASTA File',['../tutorials-fileio-fasta.html#autotoc_md56',1,'']]],
  ['a_20fastarecord_20object_1',['Step 2. Creating a FastaRecord Object',['../tutorials-fileio-fasta.html#autotoc_md55',1,'']]],
  ['a_20glance_2',['Biovoltron at a Glance',['../index.html#autotoc_md33',1,'']]],
  ['adapterassembler_3',['AdapterAssembler',['../classbiovoltron_1_1AdapterAssembler.html',1,'biovoltron']]],
  ['adaptergraph_4',['AdapterGraph',['../structbiovoltron_1_1AdapterGraph.html',1,'biovoltron']]],
  ['adaptertrimmer_5',['AdapterTrimmer',['../classbiovoltron_1_1paired_1_1AdapterTrimmer.html',1,'biovoltron::paired::AdapterTrimmer&lt; R &gt;'],['../classbiovoltron_1_1single_1_1AdapterTrimmer.html',1,'biovoltron::single::AdapterTrimmer&lt; R &gt;']]],
  ['adaptertrimmer_3c_20record_20_3e_6',['AdapterTrimmer&lt; Record &gt;',['../classbiovoltron_1_1paired_1_1AdapterTrimmer.html',1,'biovoltron::paired::AdapterTrimmer&lt; Record &gt;'],['../classbiovoltron_1_1single_1_1AdapterTrimmer.html',1,'biovoltron::single::AdapterTrimmer&lt; Record &gt;']]],
  ['adaptor_20trimming_7',['Adaptor Trimming',['../index.html#autotoc_md36',1,'']]],
  ['afcalculator_8',['AFCalculator',['../structbiovoltron_1_1AFCalculator.html',1,'biovoltron']]],
  ['algo_9',['algo',['../group__algo.html',1,'']]],
  ['algorithms_10',['8.1 Prefer using standard containers or standard algorithms',['../codingstyle.html#autotoc_md24',1,'']]],
  ['align_11',['Align',['../classbiovoltron_1_1SimdAlignmentEngine.html#a27fd7db2fefe5857dd804dcbd9858614',1,'biovoltron::SimdAlignmentEngine::Align(const char *sequence, std::uint32_t sequence_len, const Graph &amp;graph, std::int32_t *score)'],['../classbiovoltron_1_1SimdAlignmentEngine.html#a304e391b41611042591d4a25eddeb260',1,'biovoltron::SimdAlignmentEngine::Align(const char *sequence, std::uint32_t sequence_len, const Graph &amp;graph, std::int32_t *score, int method)']]],
  ['align_12',['align',['../group__align.html',1,'']]],
  ['align_20and_20variant_20calling_13',['Align and Variant Calling',['../index.html#autotoc_md35',1,'']]],
  ['alignedallocator_14',['AlignedAllocator',['../classAlignedAllocator.html',1,'']]],
  ['alignedallocator_3c_20u_2c_20alignment_20_3e_15',['AlignedAllocator&lt; U, Alignment &gt;',['../classAlignedAllocator.html',1,'']]],
  ['aligner_16',['Burrow Wheeler Aligner',['../benchmark.html#autotoc_md0',1,'']]],
  ['alignment_17',['Alignment',['../structbiovoltron_1_1Alignment.html',1,'biovoltron']]],
  ['alignment_20tutorials_18',['Alignment Tutorials',['../tutorials.html#tutorials-alignment',1,'']]],
  ['alleleutils_19',['AlleleUtils',['../classbiovoltron_1_1AlleleUtils.html',1,'biovoltron']]],
  ['aln_20',['Aln',['../structbiovoltron_1_1BurrowWheelerAligner_1_1Aln.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['alnpair_21',['AlnPair',['../structbiovoltron_1_1BurrowWheelerAligner_1_1AlnPair.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['alt_22',['alt',['../structbiovoltron_1_1VcfRecord.html#a03a582fdcf4de770cea2d0e5622cd5f2',1,'biovoltron::VcfRecord']]],
  ['anchor_23',['Anchor',['../structbiovoltron_1_1BurrowWheelerAligner_1_1Anchor.html',1,'biovoltron::BurrowWheelerAligner']]],
  ['and_20execution_20guide_24',['README: WFPOA Compilation and Execution Guide',['../md_doc_2markdown_2tutorials_2algo_2align_2wfpoa.html',1,'']]],
  ['and_20output_25',['File Input and Output',['../index.html#autotoc_md34',1,'']]],
  ['and_20running_26',['Compiling and Running',['../installation.html#autotoc_md42',1,'']]],
  ['and_20structs_27',['and Structs',['../codingstyle.html#autotoc_md9',1,'3.3. Classes and Structs'],['../codingstyle.html#autotoc_md18',1,'6. Classes and Structs']]],
  ['and_20support_28',['Community and Support',['../index.html#autotoc_md38',1,'']]],
  ['and_20variant_20calling_29',['Align and Variant Calling',['../index.html#autotoc_md35',1,'']]],
  ['annotate_30',['annotate',['../group__annotate.html',1,'']]],
  ['annotator_31',['Annotator',['../structbiovoltron_1_1Annotator.html',1,'biovoltron']]],
  ['annotator_20tutorials_32',['Annotator Tutorials',['../tutorials.html#tutorials-annotator',1,'']]],
  ['anyfield_33',['AnyField',['../structbiovoltron_1_1AnyField.html',1,'biovoltron']]],
  ['append_34',['append',['../structbiovoltron_1_1Cigar.html#a0d5d66e54cbf1e52d2d6c90e4b6e8002',1,'biovoltron::Cigar']]],
  ['applications_35',['applications',['../group__applications.html',1,'']]],
  ['assemble_36',['assemble',['../classbiovoltron_1_1AdapterAssembler.html#a269f31e75ed3c000be5391238f1be4c6',1,'biovoltron::AdapterAssembler::assemble()'],['../group__assemble.html',1,'assemble']]],
  ['assembler_37',['Assembler',['../classbiovoltron_1_1Assembler.html',1,'biovoltron']]],
  ['at_20a_20glance_38',['Biovoltron at a Glance',['../index.html#autotoc_md33',1,'']]],
  ['attrs_39',['attrs',['../structbiovoltron_1_1GffRecord.html#afd2ce8e23af19324eb91abac25292cec',1,'biovoltron::GffRecord']]],
  ['avxpairhmm_40',['AvxPairHMM',['../structbiovoltron_1_1AvxPairHMM.html',1,'biovoltron']]],
  ['avxsmithwaterman_41',['AvxSmithWaterman',['../structbiovoltron_1_1AvxSmithWaterman.html',1,'biovoltron']]]
];
