#include <biovoltron/applications/haplotypecaller/haplotypecaller.hpp>
#include <iostream> //debug
#include <catch.hpp>

using namespace biovoltron;

/*
auto
make_sam_record(const auto& seq) {
  auto record = SamRecord{};
  record.seq = seq;
  record.qual = std::string(record.seq.size(), ';');
  return record;
}

auto
ngs_sequencing(const auto& seq) {
  // NGS reads not longer than 255 base
  auto read1 = seq.substr(100, 200);
  auto read2 = seq.substr(200, 400);
  auto read3 = seq.substr(700, 900);

  auto records = std::vector<SamRecord<>>{};
  for (auto i = 0; i < 5; i++) {
    records.push_back(make_sam_record(read1));
    records.push_back(make_sam_record(read2));
    records.push_back(make_sam_record(read3));
  }

  return records;
}
*/

TEST_CASE("Haplotypecaller") {
  auto haplotype_caller = HaplotypeCaller{};
  WARN("TODO: applications/haplotypecaller/haplotypecaller.hpp requires test");

  /*
  auto ref = std::string{
    "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGCCT"
    "GCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGATCAG"
    "CCCTAACGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTGTGGATG"
    "CAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATACGATATCAA"
    "AGGTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCGGTACGGTCTAT"
    "GCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGGCATGATACCGGGG"
    "AATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCAAGAGAAGATCGTAGG"
    "CACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCACATCACGCATATTAGAC"
    "CGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTGGATTAACAAGAGTGGGGAA"
    "GCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGGGTTGCGGCCCGGCGCGGTACG"
    "TTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGCATTTTTAGATGTCTGCTGTCGGT"
    "CAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCAAATCATTAAACGCGCCCGCAGTGC"
    "TTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTACCAAAGTCTCACTGCCGTCACGGTAA"
    "GTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAATGGTGCTGAAGGCGACT"};
  auto subject = ref;
  for (auto idx = 150; idx < 155; idx++) {
    ref[idx] = 'A';
    subject[idx] = 'T';
  }
  subject.insert(subject.begin() + 300, 'T');
  subject.erase(subject.begin() + 800);

  auto reads = ngs_sequencing(subject);

  std::vector<Haplotype> haplotypes(8);
  haplotypes[0].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCTTTTTGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCG"
      "GTACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGG"
      "CATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCA"
      "AGAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCA"
      "CATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTG"
      "GATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGG"
      "GTTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGC"
      "ATTTTTAGTGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCA"
      "AATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTA"
      "CCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAAT"
      "GGTGCTGAAGGCGACT";
  haplotypes[0].align_begin_wrt_ref = 0;
  haplotypes[0].score = -0.237544;
  haplotypes[0].cigar = "150M5D5I144M1I500M1D224M";

  haplotypes[1].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCAAAAAGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCG"
      "GTACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGG"
      "CATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCA"
      "AGAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCA"
      "CATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTG"
      "GATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGG"
      "GTTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGC"
      "ATTTTTAGTGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCA"
      "AATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTA"
      "CCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAAT"
      "GGTGCTGAAGGCGACT";
  haplotypes[1].align_begin_wrt_ref = 0;
  haplotypes[1].score = -0.936514;
  haplotypes[1].cigar = "299M1I500M1D224M";

  haplotypes[2].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCTTTTTGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCGG"
      "TACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGGC"
      "ATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCAA"
      "GAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCAC"
      "ATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTGG"
      "ATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGGG"
      "TTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGCA"
      "TTTTTAGTGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCAA"
      "ATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTAC"
      "CAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAATG"
      "GTGCTGAAGGCGACT";
  haplotypes[2].align_begin_wrt_ref = 0;
  haplotypes[2].score = -0.936514;
  haplotypes[2].cigar = "150M5D5I644M1D224M";

  haplotypes[3].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCTTTTTGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCG"
      "GTACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGG"
      "CATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCA"
      "AGAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCA"
      "CATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTG"
      "GATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGG"
      "GTTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGC"
      "ATTTTTAGATGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTC"
      "AAATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGT"
      "ACCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAA"
      "TGGTGCTGAAGGCGACT";
  haplotypes[3].align_begin_wrt_ref = 0;
  haplotypes[3].score = -0.936514;
  haplotypes[3].cigar = "150M5D5I144M1I725M";

  haplotypes[4].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCAAAAAGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCG"
      "GTACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGG"
      "CATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCA"
      "AGAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCA"
      "CATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTG"
      "GATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGG"
      "GTTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGC"
      "ATTTTTAGATGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTC"
      "AAATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGT"
      "ACCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAA"
      "TGGTGCTGAAGGCGACT";
  haplotypes[4].align_begin_wrt_ref = 0;
  haplotypes[4].score = -1.63548;
  haplotypes[4].cigar = "299M1I725M";

  haplotypes[5].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCTTTTTGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCGG"
      "TACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGGC"
      "ATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCAA"
      "GAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCAC"
      "ATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTGG"
      "ATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGGG"
      "TTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGCA"
      "TTTTTAGATGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCA"
      "AATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTA"
      "CCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAAT"
      "GGTGCTGAAGGCGACT";
  haplotypes[5].align_begin_wrt_ref = 0;
  haplotypes[5].score = -1.63548;
  haplotypes[5].cigar = "150M5D5I869M";

  haplotypes[6].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCAAAAAGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCGG"
      "TACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGGC"
      "ATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCAA"
      "GAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCAC"
      "ATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTGG"
      "ATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGGG"
      "TTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGCA"
      "TTTTTAGTGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCAA"
      "ATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTAC"
      "CAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAATG"
      "GTGCTGAAGGCGACT";
  haplotypes[6].align_begin_wrt_ref = 0;
  haplotypes[6].score = -1.63548;
  haplotypes[6].cigar = "799M1D224M";

  haplotypes[7].seq
    = "AATCGAAGGTCGTAAGGACACGGTTGAGCGTTCAGCGTTCATGTGAGTCCTCACCACTTATGGCTCCATAGC"
      "CTGCTATTTAAGTGGGTTACCGGTCTCCGCCAAGTAGCTGGTGTAAGAACACAGTAACTGAGCCCAGTGTGA"
      "TCAGCCAAAAAGAGGTACCAATCATCATAAACCATCCCTTGAGTCTCGGTTCTGCTGGTTTCGGACGTCGTG"
      "TGGATGCAGCGGATTTGACTACCGTCCTCATAGGAATGCCGGATGTAATGAAACTTCCGCTTCCAAATATAC"
      "GATATCAAAGGTGTGGAGACGATGGGCGAACTTGGCAGCGGCCCCCCCCACCGGGGGTCTCCGGCGTAGCGG"
      "TACGGTCTATGCTAAGGCGTTGCTAACAATTGCAGGAGCACGGGGCTCGCAAGTAAAAGCACCGCACTGGGC"
      "ATGATACCGGGGAATACGGAGTCTTCCCTTATGCCGAAAGAAGCAGCTATAACTTCCTCGGGTAAAGGGCAA"
      "GAGAAGATCGTAGGCACGTACTCCCGAACTTCAAGAGATCCCGGTTTGCTGCGCCAACCCAATGGTAGCCAC"
      "ATCACGCATATTAGACCGTTGCTGAAATAGTAAAGGCCGCAACCTTCAGATGTCAGCCTTTTCATGCTGTGG"
      "ATTAACAAGAGTGGGGAAGCAATACGAAGTGAGTTCGTTGGGCATGCGGGAGGGCGGCAGGAAGCAAACGGG"
      "TTGCGGCCCGGCGCGGTACGTTGTGAATCGATCTCTGACGCATACCCTCCAGCAATTCCTAAAACCTCCGCA"
      "TTTTTAGATGTCTGCTGTCGGTCAGGTAGTCAACAGGTTTGTTCACCGAAACGACTGGTCTTCACCCCGTCA"
      "AATCATTAAACGCGCCCGCAGTGCTTTCACGGGTCCCCGACGTCAGATCGCCCTAGACCATGATGCCCGGTA"
      "CCAAAGTCTCACTGCCGTCACGGTAAGTGGTATATGCGGTTGGGCGGCTCTCTACTTCGGTTGATGAATAAT"
      "GGTGCTGAAGGCGACT";
  haplotypes[7].align_begin_wrt_ref = 0;
  haplotypes[7].score = -2.33445;
  haplotypes[7].cigar = "1024M";

  auto chr = Interval{"chr1:0-1024"};
  auto calling = 300;
  auto padding = 100;
  auto origin_region = Interval{chr.chrom, chr.begin, chr.begin + calling};
  auto padded_region
    = Interval{chr.chrom, chr.begin, chr.begin + calling + padding};

  std::vector<std::vector<double>> likelihoods
    = {{-3.01044, -7.51002, -3.01002, -3.01086, -7.51002, -3.01044, -7.51002,
        -7.51002},
       {-3.01044, -7.51002, -3.01002, -3.01086, -7.51002, -3.01044, -7.51002,
        -7.51002},
       {-3.01044, -7.51002, -3.01002, -3.01086, -7.51002, -3.01044, -7.51002,
        -7.51002},
       {-3.01044, -7.51002, -3.01002, -3.01086, -7.51002, -3.01044, -7.51002,
        -7.51002},
       {-3.01044, -7.51002, -3.01002, -3.01086, -7.51002, -3.01044, -7.51002,
        -7.51002}};

  // auto haplotype_caller = HaplotypeCaller{};
  // auto variants = haplotype_caller.call_region(
  //   reads, ref, padded_region, origin_region);

  // REQUIRE(variants.size() == 3);
  // REQUIRE(variants[0].location.chrom == "chr1");
  // REQUIRE(variants[0].location.begin == 149);
  // REQUIRE(variants[0].alleles[0] == "CAAAAA");
  // REQUIRE(variants[0].alleles[1] == "C");
  // REQUIRE(variants[0].gt == std::make_pair<std::uint16_t, std::uint16_t>(1, 1));

  // REQUIRE(variants[1].location.chrom == "chr1");
  // REQUIRE(variants[1].location.begin == 154);
  // REQUIRE(variants[1].alleles[0] == "A");
  // REQUIRE(variants[1].alleles[1] == "*");
  // REQUIRE(variants[1].alleles[2] == "ATTTTT");
  // REQUIRE(variants[1].gt == std::make_pair<std::uint16_t, std::uint16_t>(2, 2));

  // REQUIRE(variants[2].location.chrom == "chr1");
  // REQUIRE(variants[2].location.begin == 298);
  // REQUIRE(variants[2].alleles[0] == "G");
  // REQUIRE(variants[2].alleles[1] == "GT");
  // REQUIRE(variants[2].gt == std::make_pair<std::uint16_t, std::uint16_t>(1, 1));
  */
}
